repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort src/ --skip=main.py
        language: system
        types: [ python ]
        pass_filenames: false
      
      - id: pylint
        name: pylint
        entry: pylint --rcfile=./pylintrc src/ --ignore=main.py
        language: system
        types: [ python ]
        pass_filenames: false

