repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort src/ --skip=test_module.py,test_train.py,trash.py
        language: system
        types: [ python ]
        pass_filenames: false
      
      - id: pylint
        name: pylint
        entry: pylint --rcfile=./pylintrc src/ --ignore=test_module.py,test_train.py,trash.py --disable=W0613
        language: system
        types: [ python ]
        pass_filenames: false

